name: Telefono
version: '${version}'
main: me.zrageyh.telefono.Telefono
api-version: '1.21'
authors: [ zRageyh_ ]
description: Implementazione del telefono stile fivem
depend: [ HeadDatabase, ItemsAdder, RPGhuds ]
softdepend: [ CMI, DiscordSRV ]
libraries:
  - 'com.zaxxer:HikariCP:6.0.0'
  - 'org.mariadb.jdbc:mariadb-java-client:3.5.0'
